apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-kuberetes-batch-deployment
  labels:
    app: nagp-kuberetes-batch
spec:
  template:
    metadata:
      name: nagp-kuberetes-batch-pod
      labels:
        app: nagp-kuberetes-batch
        type: front-end
    spec:
      containers:
        - name: nodejs-container
          image: khatridarshan16/i-khatridarshan16-main
  replicas: 4
  selector:
    matchLabels:
      type: front-end
      app: nagp-kuberetes-batch