apiVersion: v1
kind: Service
metadata:
  name: nagp-kuberetes-batch
spec:
  selector:
    app: nagp-kuberetes-batch
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000